### ISSUE TITLE
ENH: bind F9 to run tab button

### ISSUE THREAD

**Issue by yw5aj** [stonebig/sqlite_bro#1]
Dear stonebig,

Awesome tool! Thank you so much for developing this. Would you think a shortcut binding of F9 to "run tab" button will enhance the interface?

(The F9 key is from how Spyder runs selected code)

Shawn

**Comment by stonebig** [comment]
Hi Shawn,

Can you pinpoint me to an example of such a key binding of tkinter on internet ? (or a pull request ?)

**Comment by yw5aj** [comment]
Hi stonebig,

Sure! I just did a PR #2 .

I have referred to two examples:

http://stackoverflow.com/questions/13326940/python-tkinter-how-to-bind-key-to-a-button
http://stackoverflow.com/questions/19895877/tkinter-cant-bind-arrow-key-events

Let me know if you have any thoughts,

Shawn

**Comment by stonebig** [comment]
I'll publish the update on pypi this week-end at latest. thanks.

**Comment by yw5aj** [comment]
Thank YOU for the excellent light-weight tool! :)

Shawn

On Wed, Aug 12, 2015 at 5:01 PM, stonebig notifications@github.com wrote:

> I'll publish the update on pypi this week-end at latest. thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stonebig/sqlite_bro/issues/1#issuecomment-130447972.

## 

Yuxiang "Shawn" Wang
Gerling Haptics Lab
University of Virginia
yw5aj@virginia.edu
+1 (434) 284-0836
https://sites.google.com/a/virginia.edu/yw5aj/

**Comment by stonebig** [comment]
Done !. In the process, I discover I forgot to publish the version before.
